name: Scrape Edreams website
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Adjust the version if needed

    - name: Install dependencies
      run: npm install

    - name: Run Playwright script
      run: node main/index.js

    - name: Commit changes
      run: |
      git config user.name ScrapingBot
      git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update latest flight offers"
      git push origin main